INCLINATIONS = [-1,1]
NETWORK_ORIGINAL_FILENAME = "startOfNetwork.json"
DATA_SIMULATION_FOLDER = "data_simulation"
ARTICLES_FILENAME = "articlesInfo.json"
# config constants
HOMOPHILY_INDEX = 0.5
NODE_COUNT = 500
EDGE_COUNT_MEAN = 50
EDGE_COUNT_VAR = 10

#article level constants
ARTICLE_POLARITY_RANGE = [0.5,1]
ARTICLE_POLARITY_MEAN = 0.75
ARTICLE_POLARITY_VAR = 0.1

ARTICLE_ATTRACTIVENESS_RANGE = [0,1]
ARTICLE_ATTRACTIVENESS_MEAN = 0.5
ARTICLE_ATTRACTIVENESS_VAR = 0.1

ARTICLE_COUNT = 3000 # this corresponds to the number of rounds which the article will go through.

ARTICLE_SAMPLER_COUNT = 10

#user level constants

